BlogTask/Models/Account/ListViewModel.cs
namespace BlogTask.Models.Account
{
    public class ListViewModel
    {
        public List<UserViewModel> UserList { get; set; }
    }
}

BlogTask/Models/Article/EditViewModel.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Article
{
    public class EditViewModel
    {
        [Required(ErrorMessage = "Поле Заголовок обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Заголовок", Prompt = "Введите заголовок статьи")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Поле Контент обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Контент", Prompt = "Введите текст статьи")]
        public string Text { get; set; }

        public Guid Guid { get; set; }
    }
}

BlogTask/Models/Article/EventViewModel.cs
namespace BlogTask.Models.Article
{
    public class EventViewModel
    {
        public string Send { get; set; }
    }
}

BlogTask/Models/Article/ListViewModel.cs
namespace BlogTask.Models.Article
{
    public class ListViewModel
    {
        public List<ArticleViewModel> List { get; set; }
    }
}

BlogTask/Models/EventViewModel.cs
namespace BlogTask.Models
{
    public class EventViewModel
    {
        public string Send { get; set; }
    }
}

BlogTask/Models/Role/EditViewModel.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Role
{
    public class EditViewModel
    {
        [Required(ErrorMessage = "Поле Название обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Название", Prompt = "Введите название роли")]
        public string Name { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Описание", Prompt = "Введите описание роли")]
        public string Description { get; set; }

        public int Id;
    }
}

BlogTask/Models/Role/ListViewModel.cs
namespace BlogTask.Models.Role
{
    public class ListViewModel
    {
        public List<RoleViewModel> List { get; set; }
    }
}

BlogTask/Models/Tag/EditViewModel.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Tag
{
    public class AddViewModel
    {
        [Required(ErrorMessage = "Поле Название обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Название", Prompt = "Введите название тега")]
        public string Name { get; set; }

        public Guid guid { get; set; }
    }
}

BlogTask/Models/Tag/ListViewModel.cs
using BlogTask.Models.Account;

namespace BlogTask.Models.Tag
{
    public class ListViewModel
    {
        public List<TagViewModel> List { get; set; }
    }
}

BlogTask/Controllers/AccountManagerController.cs
using AutoMapper;
using BlogTask.Data.Models;
using BlogTask.Data.Repositories;
using BlogTask.Data.UoW;
using BlogTask.Models.Account;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using BlogTask.Models;
using BlogTask.BLL.Services;

namespace BlogTask.Controllers
{
    [Route("[controller]")]
    public class AccountManagerController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IService<User> _userService;
        private readonly IService<Role> _roleService;
        private readonly ILogger<AccountManagerController> _logger;

        public AccountManagerController(IMapper mapper,ILogger<AccountManagerController> logger, IService<User> userService, IService<Role> roleService)
        {
            _mapper = mapper;
            _userService = userService;
            _roleService = roleService;
            _logger = logger;
            _logger.LogInformation("Создан AccountManagerController");
        }

        /// <summary>
        /// Вывод формы для регистрации
        /// </summary>
        /// <returns></returns>
        [Route("Register")]
        [HttpGet]
        public IActionResult Register()
        {
            _logger.LogInformation("Перешли на страницу Register");
            return View("Register");
        }

        /// <summary>
        /// Регистрация пользователя
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Route("Register")]
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _mapper.Map<User>(model);

                var findUser = ((UserService)_userService)?.GetByLogin(user.Login);
                if (findUser is not null) 
                {
                    _logger.LogInformation("Модель передана пустой");
                    return View("Register"); 
                }

                if (_userService is not null) { await _userService.CreateAsync(user); }

                _logger.LogInformation("Пользователь успешно зарегистрировался");
            }
            else 
            {
                _logger.LogWarning("Ошибка Верификации при регистрации");
            }
            return View("Register", model);
        }

        [Route("Login")]
        [HttpGet]
        public IActionResult Login()
        {
            _logger.LogInformation("Перешли на страницу Login");
            return View("Login");
        }

        /// <summary>
        /// Обработка данный для аутентификации
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Route("Login")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (String.IsNullOrEmpty(model.Login) || String.IsNullOrEmpty(model.Password))
                {
                    _logger.LogWarning("Логин или пароль не заданы");
                    return StatusCode(400, "Запрос не корректен!");
                }

                var user = _mapper.Map<User>(model);
                if (user is null)
                {
                    _logger.LogWarning("Модель передана пустой");
                    return StatusCode(400, "Пользователь на найден!");
                }

                if (! await PasswordIsCorrect(user))
                {
                    _logger.LogWarning("Пароль введен не правильный");
                    return StatusCode(400, "Введенный пароль не корректен!");
                }
                
                var roleId = ((UserService)_userService)?.GetByLogin(user.Login).Result.RoleId;

                var roleName = roleId is null ? "Пользователь" : _roleService?.GetAsync((int)roleId).Result.Name;
                roleName = roleName is null ? "Пользователь" : roleName;

                var claims = new List<Claim>
                {
                    new Claim(ClaimsIdentity.DefaultNameClaimType, user.Login),
                    new Claim(ClaimsIdentity.DefaultRoleClaimType, roleName)
                };

                ClaimsIdentity claimsIdentity = new(
                    claims,
                    "AddCookies",
                    ClaimsIdentity.DefaultNameClaimType,
                    ClaimsIdentity.DefaultRoleClaimType);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                _logger.LogInformation("Пользователь успешно авторизовался");
                return RedirectToAction("Index", "Home");
            }
            else
            {
                _logger.LogWarning("Ошибка Верификации при логировании");
                return View("Login", model);
            }
        }

        /// <summary>
        /// Страница по редактированию информации о пользователе
        /// </summary>
        /// <returns></returns>
        [Route("Edit")]
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(Guid guid)
        {
            var user = await _userService.GetAsync(guid);

            var editUser = _mapper.Map<User, EditUserVeiwModel>(user);

            _logger.LogInformation("Перешли на страницу Редактирования пользователя");

            return View("Edit", editUser);
        }

        /// <summary>
        /// Обработка результата редактирования пользователя
        /// </summary>
        /// <returns></returns>
        [Route("Edit")]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(EditUserVeiwModel model)
        {
            var editUser = await _userService.GetAsync(model.Guid);

            if (ModelState.IsValid)
            {

                bool isUpdate = false;

                if (editUser.Login != model.Login)
                {
                    editUser.Login = model.Login;
                    isUpdate = true;
                }
                if (editUser.FirstName != model.FirstName)
                {
                    editUser.FirstName = model.FirstName;
                    isUpdate = true;
                }
                if (editUser.LastName != model.LastName)
                {
                    editUser.LastName = model.LastName;
                    isUpdate = true;
                }
                if (editUser.SurName != model.SurName)
                {
                    editUser.SurName = model.SurName is null ? "" : model.SurName;
                    isUpdate = true;
                }
                if (editUser.Password != model.Password)
                {
                    editUser.Password = model.Password;
                    isUpdate = true;
                }

                if (isUpdate)
                {
                    await _userService.UpdateAsync(editUser);
                }

                _logger.LogInformation("Данные о пользователе успешно изменены");

                return await ListAsync();
            }
            else
            {
                _logger.LogWarning("Ошибка Верификации при редактировании пользователя");
                return View("Edit", model);
            }
        }

        /// <summary>
        /// Страница по редактированию информации о пользователе
        /// </summary>
        /// <returns></returns>
        [Route("View")]
        [HttpGet]
        public async Task<IActionResult> ViewUser(Guid guid)
        {
            var user = await _userService.GetAsync(guid);
            UserViewModel model = new();

            if (user is not null)
            {
                model = _mapper.Map<User, UserViewModel>(user);

                var role = await _roleService.GetAsync((int)user.RoleId);

                if (role != null)
                {
                    model.Role = role;
                }
            }

            _logger.LogInformation("Перешли на страницу просмотра информации о пользователе");

            return View(model);
        }

        /// <summary>
        /// Страница информации о текущем пользователе
        /// </summary>
        /// <returns></returns>
        [Route("Profile")]
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Profile()
        {
            var login = User.Identity.Name;

            var user = await ((UserService)_userService).GetByLogin(login);

            UserViewModel model = new();

            if (user is not null)
            {
                model = _mapper.Map<User, UserViewModel>(user);

                var role = await _roleService.GetAsync((int)user.RoleId);

                if (role != null)
                {
                    model.Role = role;
                }
            }

            _logger.LogInformation("Перешли на страницу просмотра информации о себе");

            return View("ViewUser", model);
        }

        /// <summary>
        /// Получить список пользователей
        /// </summary>       
        /// <returns></returns>
        [Route("List")]
        [HttpGet]
        public async Task<IActionResult> ListAsync()
        {
            var listUsers = _userService.GetAllAsync().Result.ToList();

            if (listUsers == null)
            {
                _logger.LogWarning("Пользователи на сайте отсутствуют");
                return View("Event", new EventViewModel() { Send = "Пользователи отсутствуют!" });
            }
            if (listUsers.Count == 0)
            {
                _logger.LogWarning("Пользователи на сайте отсутствуют");
                return View("Event", new EventViewModel() { Send = "Пользователи отсутствуют!" });
            }

            foreach (var user in listUsers)
            {

BlogTask/Views/AccountManager/Edit.cshtml
@model BlogTask.Models.Account.EditUserVeiwModel;

@{
    ViewData["Title"] = "Редактирование пользователя";
}

<partial name="_ValidationScriptsPartial" />

@if (Model is not null)
{
    <div class="container my-1">
        <div class="p-1">

            <h3>Изменить данные пользователя @Model.Login</h3>

            <form method="post" asp-controller="AccountManager" asp-action="Edit">
                <div class="mb-3">
                    <label for="Title" class="form-label">Логин</label>
                    <span asp-validation-for="Login" class="text-danger"></span>
                    <input type="text" asp-for="Login" class="form-control" id="Title">
                </div>
                <div class="mb-3">
                    <label for="FirstName" class="form-label">Имя</label>
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                    <textarea type="text" asp-for="FirstName" class="form-control" id="FirstName"> </textarea>
                </div>
                <div class="mb-3">
                    <label for="LastName" class="form-label">Фамилия</label>
                    <span asp-validation-for="LastName" class="text-danger"></span>
                    <textarea type="text" asp-for="LastName" class="form-control" id="InpLastNameutText"> </textarea>
                </div>
                <div class="mb-3">
                    <label for="SurName" class="form-label">Отчество</label>
                    <span asp-validation-for="SurName" class="text-danger"></span>
                    <textarea type="text" asp-for="SurName" class="form-control" id="SurName"> </textarea>
                </div>
                <div class="mb-3">
                    <label for="Password" class="form-label">Пароль</label>
                    <span asp-validation-for="Password" class="text-danger"></span>
                    <input type="password" asp-for="Password" class="form-control" id="Password">
                </div>
                <input type="text" asp-for="Guid" hidden />
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
    </div>
}

BlogTask/Views/AccountManager/Event.cshtml
@if (Model is not null)
{
    ViewData["Title"] = Model.Send;
}
else
{
    ViewData["Title"] = "Предуприждение!";
}

BlogTask/Views/AccountManager/Index.cshtml
@{
    ViewData["Title"] = "Вход";
}
<div class="main">
    <partial name="Login"/>
</div>

BlogTask/Views/AccountManager/List.cshtml
@model BlogTask.Models.Account.ListViewModel;

@{
    ViewData["Title"] = "Просмотр списка пользователей";
}

@if (Model.UserList.Count != 0)
{
    <div class="container my-1">
        <h3 class="text-center">Просмотр списка пользователей</h3>

        @foreach (var user in @Model.UserList)
        {
            <div class="p-1">
                @{
                    RouteValueDictionary get = new RouteValueDictionary();
                    get["guid"] = user.Guid;
                }
                <div class="card rounded-3">
                    <h5 class="card-header border-0" cursor="pointer" role="button" onclick="location.href = '@Url.Action("View", get)'">@user.Login</h5>
                    <div class="card-body">
                        <h6>@user.GetFullName()</h6>
                        @if (user.Role is not null)
                        {
                            <span class="badge bg-primary">@user.Role.Name</span>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
}

BlogTask/Views/AccountManager/UserList.cshtml
@model BlogTask.Models.Account.ListViewModel;

@if (Model.UserList.Count != 0)
{
    @foreach (var user in @Model.UserList)
    {
        <div class="card">
            <h5 class="card-header">Имя пользователя</h5>
            <div class="card-body">
                <h5 class="card-title">Special title treatment</h5>
                <span class="badge bg-primary">Роли</span>
            </div>
        </div>
    }
}

BlogTask/Views/AccountManager/ViewUser.cshtml
@model BlogTask.Models.Account.UserViewModel;

@{
    ViewData["Title"] = "Информация о пользователе";
}

@if (Model is not null)
{
    <div class="container my-1">
        <h3>Информация о пользователе</h3>
        <div class="p-1">
            <div class="card rounded-3">
                <h5 class="card-header border-0">@Model.GetFullName()</h5>
                <div class="card-body">
                    @{
                        RouteValueDictionary get = new RouteValueDictionary();
                        get["guid"] = @Model.Guid;
                    }

                    <span class="badge bg-primary" style="display:inline;">@Model.Role.Name</span>

                    
                    @if (@Model is not null)
                    {
                        <p class="text-decoration-underline">@Model.Login</p>

                        @if (Model.Login == User.Identity.Name)
                        {
                            <div class="p-1">
                                <button type="button" class="btn btn-success btn-sm" onclick="window.location='@Url.Action("Edit", get)'">Редактировать</button>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
}