BlogTask/Models/Account/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Account
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Поле Логин обязательно для заполнения")]
        [DataType(DataType.Text)]
        public string Login { get; set; }

        [Required(ErrorMessage = "Поле Пароль обязательно для заполнения")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

BlogTask/Models/Account/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Account
{
    public class RegisterViewModel
    {
        [Required(ErrorMessage = "Поле Имя обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Имя", Prompt = "Введите имя")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Поле Фамилия обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Фамилия", Prompt = "Введите фамилию")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Поле Логин обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Логин", Prompt = "Введите логин")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Поле Пароль обязательно для заполнения")]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль", Prompt = "Введите пароль")]
        [StringLength(100, ErrorMessage = "Поле {0} должно иметь минимум {2} и максимум {1} символов.", MinimumLength = 5)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Поле проверки Пароля обязательно для заполнения")]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль", Prompt = "Введите пароль повторно")]
        [StringLength(100, ErrorMessage = "Поле {0} должно иметь минимум {2} и максимум {1} символов.", MinimumLength = 5)]
        public string PasswordConfirm { get; set; }
    }
}

BlogTask/Controllers/RoleController.cs
using AutoMapper;
using BlogTask.BLL.Services;
using BlogTask.Data.Models;
using BlogTask.Data.Repositories;
using BlogTask.Data.UoW;
using BlogTask.Models;
using BlogTask.Models.Role;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogTask.Controllers
{
    [Route("[controller]")]
    public class RoleController : Controller
    {
        private readonly IService<Role> _roleService;
        private readonly IService<User> _userService;
        private readonly IMapper _mapper;
        private readonly ILogger<Role> _logger;

        public RoleController(IMapper mapper, ILogger<Role> logger, IService<Role> roleService, IService<User> userService)
        {
            _userService = userService;
            _roleService = roleService;
            _mapper = mapper;
            _logger = logger;
            _logger.LogInformation("Создан RoleController");
        }

        /// <summary>
        /// Вывод формы для добавления роли
        /// </summary>
        /// <returns></returns>
        [Route("Add")]
        [HttpGet]
        [Authorize]
        public IActionResult Add()
        {
            _logger.LogInformation("Пользователь перешел на страницу добавления роли");
            return View();
        }

        /// <summary>
        /// Обработка данных для добавления роли
        /// </summary>
        /// <returns></returns>
        [Route("Add")]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(AddViewModel model)
        {
            var userName = User.Identity.Name;

            var user = await ((UserService)_userService).GetByLogin(userName);

            if (model is null)
            {
                _logger.LogWarning("Данные на странице добавления роли не внесены");
                return StatusCode(400, "Данные не внесены!");
            }

            if (user.RoleId != 1)
            {
                _logger.LogWarning("Отсутствует необходимая роль для добавления роли");
                return StatusCode(400, "Отсутствует необходимая роль!");
            }

            if (ModelState.IsValid)
            {

                var newRole = _mapper.Map<AddViewModel, Role>(model);

                await _roleService.CreateAsync(newRole);

                _logger.LogInformation("Роль успешно добавлена");

                return List();
            }
            else
            {
                _logger.LogWarning("Данные при добавлении роли не прошли валидацию");
                return View(model);
            }
        }

        /// <summary>
        /// Вывод формы для редактирования роли
        /// </summary>
        /// <returns></returns>
        [Route("Edit")]
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> EditAsync(int guid)
        {
            var role = await _roleService.GetAsync(guid);

            var editRole = _mapper.Map<Role, EditViewModel>(role);

            _logger.LogInformation("Пользователь перешел на страницу редактирования роли");

            return View(editRole);
        }

        /// <summary>
        /// Обработка данных для редактирования роли
        /// </summary>
        /// <returns></returns>
        [Route("Edit")]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(EditViewModel model)
        {
            var editRole = await _roleService.GetAsync(model.Id);

            if (model is null)
            {
                _logger.LogWarning("Данные при редактировании роли не внесены");
                return StatusCode(400, "Данные не внесены!");
            }

            if (ModelState.IsValid)
            {
                bool isUpdate = false;

                if (editRole.Name != model.Name)
                {
                    editRole.Name = model.Name;
                    isUpdate = true;
                }
                if (editRole.Description != model.Description)
                {
                    editRole.Description = model.Description;
                    isUpdate = true;
                }

                if (isUpdate)
                {
                    await _roleService.UpdateAsync(editRole);
                }

                _logger.LogInformation("Роль успешно изменена");

                return List();
            }
            else
            {
                _logger.LogWarning("Данные при редактировании роли не прошли валидацию");
                return View(model);
            }
        }

        /// <summary>
        /// Вывод списка ролей
        /// </summary>
        /// <returns></returns>
        [Route("List")]
        [HttpGet]
        public IActionResult List()
        {
            var listArticles = _roleService.GetAllAsync().Result.ToList();

            if (listArticles == null)
            {
                _logger.LogWarning("Роли отсутствуют");
                return View("Event", new EventViewModel() { Send = "Роли отсутствуют!" });
            }
            if (listArticles.Count == 0)
            {
                _logger.LogWarning("Роли отсутствуют");
                return View("Event", new EventViewModel() { Send = "Роли отсутствуют!" });
            }

            ListViewModel view = new()
            {
                List = _mapper.Map<List<Role>, List<RoleViewModel>>(listArticles)
            };

            _logger.LogInformation("Пользователь перешел на страницу просмотра списка ролей");

            return View("List", view);
        }

        /// <summary>
        /// просмотр информации о роли
        /// </summary>
        /// <returns></returns>
        [Route("View")]
        [HttpGet]
        public async Task<IActionResult> ViewRoleAsync(int guid)
        {
            var role = await _roleService.GetAsync(guid);
            RoleViewModel model = new();

            if (role is not null)
            {
                _logger.LogWarning("Роль отсутствуют");
                model = _mapper.Map<Role, RoleViewModel>(role);
            }

            _logger.LogInformation("Пользователь перешел на страницу просмотра роли");

            return View(model);
        }

        /// <summary>
        /// Метод для удаления роли
        /// </summary>
        /// <param name="guid"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("Del")]
        [Authorize]
        public async Task<IActionResult> Del(int guid)
        {
            var role = await _roleService.GetAsync(guid);
            if (role == null)
            {
                _logger.LogWarning("Роль не найдена");
                return StatusCode(400, "Роль не найдена!");
            }

            await _roleService.DeleteAsync(role);

            _logger.LogInformation("Удаление роли прошло успешно");

            return List();
        }
    }
}

BlogTask/Controllers/TagController.cs
using AutoMapper;
using BlogTask.Data.Models;
using BlogTask.Data.Repositories;
using BlogTask.Data.UoW;
using BlogTask.Models;
using Microsoft.AspNetCore.Mvc;
using BlogTask.Models.Tag;
using Microsoft.AspNetCore.Authorization;
using BlogTask.BLL.Services;

namespace BlogTask.Controllers
{
    [Route("[controller]")]
    public class TagController : Controller
    {
        private readonly IService<User> _userService;
        private readonly IService<Tag> _tagService;
        private readonly IMapper _mapper;
        private readonly ILogger<Tag> _logger;

        public TagController(IMapper mapper, ILogger<Tag> logger, IService<Tag> tagService, IService<User> userService)
        {
            _userService = userService;
            _tagService = tagService;
            _mapper = mapper;
            _logger = logger;
        }

        /// <summary>
        /// Вывод формы для добавления тега
        /// </summary>
        /// <returns></returns>
        [Route("Add")]
        [HttpGet]
        [Authorize]
        public IActionResult Add()
        {
            _logger.LogInformation("Пользователь перешел на страницу добавления тега");
            return View();
        }

        /// <summary>
        /// Обработка данных для добавления тега
        /// </summary>
        /// <returns></returns>
        [Route("Add")]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(AddViewModel model)
        {
            var userName = User.Identity.Name;

            var user = await ((UserService)_userService).GetByLogin(userName);

            if (model is null)
            {
                _logger.LogWarning("Данные для добавлении тега не внесены");
                return StatusCode(400, "Данные не внесены!");
            }

            if (user.RoleId != 2)
            {
                _logger.LogWarning("Отсутствует необходимая роль для добавления тега");
                return StatusCode(400, "Отсутствует необходимая роль!");
            }

            if (ModelState.IsValid)
            {
                var newTag = _mapper.Map<AddViewModel, Tag>(model);

                await _tagService.CreateAsync(newTag);

                _logger.LogInformation("Тег успешно добавлена");

                return List();
            }
            else
            {
                _logger.LogWarning("Данные для добавлении тега не прошли валидацию");
                return View(model);
            }
        }

        /// <summary>
        /// Вывод формы для добавления тега
        /// </summary>
        /// <returns></returns>
        [Route("Edit")]
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(Guid guid)
        {
            var tag = await _tagService.GetAsync(guid);

            var editTag = _mapper.Map<Tag, EditViewModel>(tag);

            _logger.LogInformation("Пользователь перешел на страницу редактирования тега");

            return View(editTag);
        }

        /// <summary>
        /// Обработка данных для редактирования статьи
        /// </summary>
        /// <returns></returns>
        [Route("Edit")]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(EditViewModel model)
        {
            var editTag = await _tagService.GetAsync(model.Guid);

            if (model is null)
            {
                _logger.LogWarning("Данные для редактирования тега не внесены");
                return StatusCode(400, "Данные не внесены!");
            }

            if (ModelState.IsValid)
            {
                if (editTag.Name != model.Name)
                {
                    editTag.Name = model.Name;
                    await _tagService.UpdateAsync(editTag);
                }

                _logger.LogInformation("Тег успешно изменен");

                return List();
            }
            else
            {
                _logger.LogWarning("Данные для редактирования тега не прошли валидацию");
                return View(model);
            }
        }

        /// <summary>
        /// Вывод списка тегов
        /// </summary>
        /// <returns></returns>
        [Route("List")]
        [HttpGet]
        public IActionResult List()
        {
            var listTags = _tagService.GetAllAsync().Result.ToList();

            if (listTags == null)
            {
                _logger.LogWarning("Теги отсутствуют");
                return View("Event", new EventViewModel() { Send = "Теги отсутствуют!" });
            }
            if (listTags.Count == 0)
            {
                _logger.LogWarning("Теги отсутствуют");
                return View("Event", new EventViewModel() { Send = "Теги отсутствуют!" });
            }

            ListViewModel view = new()
            {
                List = _mapper.Map<List<Tag>, List<TagViewModel>>(listTags)
            };

            _logger.LogInformation("Пользователь перешел на страницу просмотра всех тегов");

            return View("List", view);
        }

        /// <summary>
        /// Вывод информации о теге
        /// </summary>
        /// <returns></returns>
        [Route("View")]
        [HttpGet]
        public async Task<IActionResult> ViewTagAsync(Guid guid)
        {
            var tag = await _tagService.GetAsync(guid);
            TagViewModel model = new();

            if (tag is not null)
            {
                _logger.LogWarning("Тег отсутствует");
                model = _mapper.Map<Tag, TagViewModel>(tag);
            }

            _logger.LogInformation("Пользователь перешел на страницу просмотра тега");

            return View(model);
        }

        /// <summary>
        /// Метод для удаления тега
        /// </summary>
        /// <param name="guid"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("Del")]
        [Authorize]
        public async Task<IActionResult> Del(Guid guid)
        {
            var tag = _tagService.GetAsync(guid);
            if (tag == null)
            {
                _logger.LogWarning("Тег отсутствует");
                return StatusCode(400, "Тэг не найден!");
            }

            await _tagService.DeleteAsync(await tag);

            _logger.LogInformation("Тег успешно удален");

            return List();
        }
    }
}

BlogTask/Views/Shared/Login.cshtml
@model BlogTask.Models.Account.LoginViewModel;

<partial name="_ValidationScriptsPartial" />

<link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />

<div class="login-page">
    <div class="form">
        <form class="login-form" method="post" asp-controller="AccountManager" asp-action="Login">
            <span asp-validation-for="Login" class="text-danger"></span>
            <input type="text" asp-for="Login" placeholder="логин" />
            <span asp-validation-for="Password" class="text-danger"></span>
            <input type="password" asp-for="Password" placeholder="пароль" />
            <button>Вход</button>
            <p class="message">Не зарегистрированы? <a href="Register">Создайте аккаунт</a></p>
        </form>
    </div>
</div>

BlogTask/Views/Shared/Register.cshtml
@{
    ViewData["Title"] = "Регистрация";
}

@model BlogTask.Models.Account.RegisterViewModel;

<partial name="_ValidationScriptsPartial" />

<link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />

<div class="login-page">
    <div class="form">
        <form class="register-form" method="post" asp-controller="AccountManager" asp-action="Register">
            <span asp-validation-for="Login" class="text-danger"></span>
            <input type="text" asp-for="Login" placeholder="логин" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
            <input type="text" asp-for="FirstName" placeholder="имя" />
            <span asp-validation-for="LastName" class="text-danger"></span>
            <input type="text" asp-for="LastName" placeholder="фамилия" />
            <div class="alert alert-warning" role="alert" for="Password" hidden id="Message">
                Пароли не совпадают!
            </div>
            <span asp-validation-for="Password" class="text-danger"></span>
            <input type="password" asp-for="Password" placeholder="пароль" id="Password" oninput="MatchPassword()" />
            <span asp-validation-for="PasswordConfirm" class="text-danger"></span>
            <input type="password" asp-for="PasswordConfirm" placeholder="повторите пароль" id="PasswordConfirm" oninput="MatchPassword()" />            
            <button id="Reg">Зарегистрироваться</button>
            <p class="message">Уже зарегистрирован? <a href="Login">Выполните вход</a></p>
        </form>
    </div>
    <script type="text/javascript">
        function MatchPassword() {
            var pass = document.getElementById("Password");
            var passConf = document.getElementById("PasswordConfirm");
            var reg = document.getElementById("Reg");
            var message = document.getElementById("Message");

            if (pass.value != passConf.value) {
                reg.removeAttribute('enabled');
                reg.setAttribute('disabled', 'disabled');
                message.hidden = false;
            }
            else {
                reg.removeAttribute('disabled');
                reg.setAttribute('enabled', 'enabled');
                message.hidden = true;
            }
        }
    </script>
</div>

BlogTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Блог</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/icon.png">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Article" asp-action="List">Статьи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Tag" asp-action="List">Тэги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="AccountManager" asp-action="List">Пользователи</a>
                        </li>
                        @if (User.IsInRole("Администратор"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Role" asp-action="List">Роли</a>
                            </li>
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form asp-controller="AccountManager" asp-action="Logout">
                            <ul class="navbar-nav flex-grow-1 justify-content-center">
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="AccountManager" asp-action="Profile">@User.Identity.Name</a>
                                </li>

                                <button class="btn btn-outline-success" id="Exit">Выход</button>
                            </ul>
                        </form>
                    }
                    else
                    {
                        <form method="get" asp-controller="AccountManager" asp-action="Login">
                            <ul class="navbar-nav flex-grow-1 justify-content-center">
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="AccountManager" asp-action="Register">Регистрация</a>
                                </li>
                                <button class="btn btn-success">Вход</button>
                            </ul>
                        </form>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - Разработка персонального блога
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>