BlogTask/Models/Account/ListViewModel.cs
namespace BlogTask.Models.Account
{
    public class ListViewModel
    {
        public List<UserViewModel> UserList { get; set; }
    }
}

BlogTask/Models/Article/AddViewModel.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Article
{
    public class AddViewModel
    {
        [Required(ErrorMessage = "Поле Заголовок обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Заголовок", Prompt = "Введите заголовок статьи")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Поле Контент обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Контент", Prompt = "Введите текст статьи")]
        public string Text { get; set; }
    }
}

BlogTask/Models/Article/EditViewModel.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Article
{
    public class EditViewModel
    {
        [Required(ErrorMessage = "Поле Заголовок обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Заголовок", Prompt = "Введите заголовок статьи")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Поле Контент обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Контент", Prompt = "Введите текст статьи")]
        public string Text { get; set; }

        public Guid Guid { get; set; }
    }
}

BlogTask/Models/Article/EventViewModel.cs
namespace BlogTask.Models.Article
{
    public class EventViewModel
    {
        public string Send { get; set; }
    }
}

BlogTask/Models/Article/ListViewModel.cs
namespace BlogTask.Models.Article
{
    public class ListViewModel
    {
        public List<ArticleViewModel> List { get; set; }
    }
}

BlogTask/Models/EventViewModel.cs
namespace BlogTask.Models
{
    public class EventViewModel
    {
        public string Send { get; set; }
    }
}

BlogTask/Models/Role/AddViewModel.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Role
{
    public class AddViewModel
    {
        [Required(ErrorMessage = "Поле Название обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Название", Prompt = "Введите название роли")]
        public string Name { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Описание", Prompt = "Введите описание роли")]
        public string Description { get; set; }
    }
}

BlogTask/Models/Role/EditViewModel.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Role
{
    public class EditViewModel
    {
        [Required(ErrorMessage = "Поле Название обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Название", Prompt = "Введите название роли")]
        public string Name { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Описание", Prompt = "Введите описание роли")]
        public string Description { get; set; }

        public int Id;
    }
}

BlogTask/Models/Role/ListViewModel.cs
namespace BlogTask.Models.Role
{
    public class ListViewModel
    {
        public List<RoleViewModel> List { get; set; }
    }
}

BlogTask/Models/Role/RoleViewModel.cs
namespace BlogTask.Models.Role
{
    public class RoleViewModel : Data.Models.Role
    {
    }
}

BlogTask/Models/Tag/AddViewModel.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Tag
{
    public class EditViewModel
    {
        [Required(ErrorMessage = "Поле Название обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Название", Prompt = "Введите название тега")]
        public string Name { get; set; }

        public Guid Guid { get; set; }
    }
}

BlogTask/Models/Tag/EditViewModel.cs
using Microsoft.Identity.Client;
using System.ComponentModel.DataAnnotations;

namespace BlogTask.Models.Tag
{
    public class AddViewModel
    {
        [Required(ErrorMessage = "Поле Название обязательно для заполнения")]
        [DataType(DataType.Text)]
        [Display(Name = "Название", Prompt = "Введите название тега")]
        public string Name { get; set; }

        public Guid guid { get; set; }
    }
}

BlogTask/Models/Tag/ListViewModel.cs
using BlogTask.Models.Account;

namespace BlogTask.Models.Tag
{
    public class ListViewModel
    {
        public List<TagViewModel> List { get; set; }
    }
}

BlogTask/Controllers/ArticleController.cs
using AutoMapper;
using BlogTask.BLL.Services;
using BlogTask.Data.Models;
using BlogTask.Data.Repositories;
using BlogTask.Data.UoW;
using BlogTask.Models;
using BlogTask.Models.Article;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogTask.Controllers
{
    [Route("[controller]")]
    public class ArticleController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IService<User> _userService;
        private readonly IService<Article> _articleService;
        private readonly ILogger<Article> _logger;

        public ArticleController(IMapper mapper, IService<Article> articleService, IService<User> userService, ILogger<Article> logger)
        {
            _mapper = mapper;
            _userService = userService;
            _articleService = articleService;
            _logger = logger;
            _logger.LogInformation("Создан AccountManagerController");
        }

        /// <summary>
        /// Вывод формы для добавления статьи
        /// </summary>
        /// <returns></returns>
        [Route("Add")]
        [HttpGet]
        [Authorize]
        public IActionResult Add()
        {
            _logger.LogInformation("Пользователь перешел на страницу добавления статьи");
            return View();
        }

        /// <summary>
        /// Обработка данных для добавления статьи
        /// </summary>
        /// <returns></returns>
        [Route("Add")]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(AddViewModel model)
        {
            var userName = User.Identity.Name;

            var user = await ((UserService)_userService).GetByLogin(userName);

            if (model is null)
            {
                _logger.LogWarning("Данные на странице добавления статьи не внесены");
                return StatusCode(400, "Данные не внесены!");
            }

            if (ModelState.IsValid)
            {
                var newArticle = _mapper.Map<AddViewModel, Article>(model);
                newArticle.UserGuid = user.Guid;
                await _articleService.CreateAsync(newArticle);

                _logger.LogInformation("Статья успешно добавлена");

                return await ListAsync();
            }
            else
            {
                _logger.LogWarning("Данные при добавлении статьи не прошли валидацию");
                return View(model);
            }
        }

        /// <summary>
        /// Вывод формы для добавления статьи
        /// </summary>
        /// <returns></returns>
        [Route("Edit")]
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(Guid guid)
        {
            var article = await _articleService.GetAsync(guid);

            var editArticle = _mapper.Map<Article, EditViewModel>(article);

            _logger.LogInformation("Пользователь перешел на страницу изменения статьи");

            return View(editArticle);
        }

        /// <summary>
        /// Обработка данных для редактирования статьи
        /// </summary>
        /// <returns></returns>
        [Route("Edit")]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(EditViewModel model)
        {
            var editArticle = await _articleService.GetAsync(model.Guid);

            if (model is null)
            {
                _logger.LogWarning("Данные изменения статьи не внесены");
                return StatusCode(400, "Данные не внесены!");
            }

            if (ModelState.IsValid)
            {
                bool isUpdate = false;

                if (editArticle.Title != model.Title)
                {
                    editArticle.Title = model.Title;
                    isUpdate = true;
                }
                if (editArticle.Text != model.Text)
                {
                    editArticle.Text = model.Text;
                    isUpdate = true;
                }

                if (isUpdate)
                {

                    await _articleService.UpdateAsync(editArticle);
                }

                _logger.LogInformation("Статья успешно изменена");

                return await ListAsync();
            }
            else
            {
                _logger.LogWarning("Данные для изменения статьи не прошли валидацию");
                return View(model);
            }
        }

        /// <summary>
        /// Вывод списка статей
        /// </summary>
        /// <returns></returns>
        [Route("List")]
        [HttpGet]
        public async Task<IActionResult> ListAsync()
        {
            var listArticles = _articleService.GetAllAsync().Result.ToList();

            if (listArticles == null)
            {
                _logger.LogWarning("Статьи отсутствуют");
                return View("Event", new EventViewModel() { Send = "Статьи отсутствуют!" });
            }
            if (listArticles.Count == 0)
            {
                _logger.LogWarning("Статьи отсутствуют");
                return View("Event", new EventViewModel() { Send = "Статьи отсутствуют!" });
            }

            ListViewModel view = new()
            {
                List = _mapper.Map<List<Article>, List<ArticleViewModel>>(listArticles)
            };

            _logger.LogInformation("Пользователь перешел на страницу просмотра всех статей");

            return View("List", view);
        }

        /// <summary>
        /// Просмотр статьи
        /// </summary>
        /// <returns></returns>
        [Route("View")]
        [HttpGet]
        public async Task<IActionResult> ViewArticle(Guid guid)
        {
            var article = await _articleService.GetAsync(guid);
            ArticleViewModel model = new();

            if (article is not null)
            {
                _logger.LogInformation("Статья отсутствует");
                model = _mapper.Map<Article, ArticleViewModel>(article);
            }

            _logger.LogInformation("Пользователь перешел на страницу просмотра статьи");

            return View(model);
        }
    }
}

BlogTask/Controllers/RoleController.cs
using AutoMapper;
using BlogTask.BLL.Services;
using BlogTask.Data.Models;
using BlogTask.Data.Repositories;
using BlogTask.Data.UoW;
using BlogTask.Models;
using BlogTask.Models.Role;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogTask.Controllers
{
    [Route("[controller]")]
    public class RoleController : Controller
    {
        private readonly IService<Role> _roleService;
        private readonly IService<User> _userService;
        private readonly IMapper _mapper;
        private readonly ILogger<Role> _logger;

        public RoleController(IMapper mapper, ILogger<Role> logger, IService<Role> roleService, IService<User> userService)
        {
            _userService = userService;
            _roleService = roleService;
            _mapper = mapper;
            _logger = logger;
            _logger.LogInformation("Создан RoleController");
        }

        /// <summary>
        /// Вывод формы для добавления роли
        /// </summary>
        /// <returns></returns>
        [Route("Add")]
        [HttpGet]
        [Authorize]
        public IActionResult Add()
        {
            _logger.LogInformation("Пользователь перешел на страницу добавления роли");
            return View();
        }

        /// <summary>
        /// Обработка данных для добавления роли
        /// </summary>
        /// <returns></returns>
        [Route("Add")]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(AddViewModel model)
        {
            var userName = User.Identity.Name;

            var user = await ((UserService)_userService).GetByLogin(userName);

            if (model is null)
            {
                _logger.LogWarning("Данные на странице добавления роли не внесены");
                return StatusCode(400, "Данные не внесены!");
            }

            if (user.RoleId != 1)
            {
                _logger.LogWarning("Отсутствует необходимая роль для добавления роли");
                return StatusCode(400, "Отсутствует необходимая роль!");
            }

            if (ModelState.IsValid)
            {

                var newRole = _mapper.Map<AddViewModel, Role>(model);

                await _roleService.CreateAsync(newRole);

                _logger.LogInformation("Роль успешно добавлена");

                return List();
            }
            else
            {
                _logger.LogWarning("Данные при добавлении роли не прошли валидацию");
                return View(model);
            }
        }

        /// <summary>
        /// Вывод формы для редактирования роли
        /// </summary>
        /// <returns></returns>
        [Route("Edit")]
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> EditAsync(int guid)
        {
            var role = await _roleService.GetAsync(guid);

            var editRole = _mapper.Map<Role, EditViewModel>(role);

            _logger.LogInformation("Пользователь перешел на страницу редактирования роли");

            return View(editRole);
        }

        /// <summary>
        /// Обработка данных для редактирования роли
        /// </summary>
        /// <returns></returns>
        [Route("Edit")]
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(EditViewModel model)
        {
            var editRole = await _roleService.GetAsync(model.Id);

            if (model is null)
            {
                _logger.LogWarning("Данные при редактировании роли не внесены");
                return StatusCode(400, "Данные не внесены!");
            }

            if (ModelState.IsValid)
            {
                bool isUpdate = false;

                if (editRole.Name != model.Name)
                {
                    editRole.Name = model.Name;
                    isUpdate = true;
                }
                if (editRole.Description != model.Description)
                {
                    editRole.Description = model.Description;
                    isUpdate = true;
                }

                if (isUpdate)
                {
                    await _roleService.UpdateAsync(editRole);
                }

                _logger.LogInformation("Роль успешно изменена");

                return List();
            }
            else
            {
                _logger.LogWarning("Данные при редактировании роли не прошли валидацию");
                return View(model);
            }
        }

        /// <summary>
        /// Вывод списка ролей
        /// </summary>
        /// <returns></returns>
        [Route("List")]
        [HttpGet]
        public IActionResult List()
        {
            var listArticles = _roleService.GetAllAsync().Result.ToList();

            if (listArticles == null)
            {
                _logger.LogWarning("Роли отсутствуют");
                return View("Event", new EventViewModel() { Send = "Роли отсутствуют!" });
            }
            if (listArticles.Count == 0)
            {
                _logger.LogWarning("Роли отсутствуют");
                return View("Event", new EventViewModel() { Send = "Роли отсутствуют!" });
            }

            ListViewModel view = new()
            {
                List = _mapper.Map<List<Role>, List<RoleViewModel>>(listArticles)
            };

            _logger.LogInformation("Пользователь перешел на страницу просмотра списка ролей");

            return View("List", view);
        }

        /// <summary>
        /// просмотр информации о роли
        /// </summary>
        /// <returns></returns>
        [Route("View")]
        [HttpGet]
        public async Task<IActionResult> ViewRoleAsync(int guid)
        {
            var role = await _roleService.GetAsync(guid);
            RoleViewModel model = new();

            if (role is not null)
            {
                _logger.LogWarning("Роль отсутствуют");
                model = _mapper.Map<Role, RoleViewModel>(role);
            }

            _logger.LogInformation("Пользователь перешел на страницу просмотра роли");

            return View(model);
        }

        /// <summary>
        /// Метод для удаления роли
        /// </summary>
        /// <param name="guid"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("Del")]
        [Authorize]
        public async Task<IActionResult> Del(int guid)
        {
            var role = await _roleService.GetAsync(guid);
            if (role == null)
            {
                _logger.LogWarning("Роль не найдена");
                return StatusCode(400, "Роль не найдена!");
            }

            await _roleService.DeleteAsync(role);

            _logger.LogInformation("Удаление роли прошло успешно");

            return List();
        }
    }
}

BlogTask/Views/Role/Add.cshtml
@model BlogTask.Models.Role.AddViewModel;

@{
    ViewData["Title"] = "Добавление роли";
}

<partial name="_ValidationScriptsPartial" />

<div class="container my-1">
    <div class="p-1">

        <h3>Добавить роль</h3>

        <form method="post" asp-controller="Role" asp-action="Add">
            <div class="mb-3">
                <label for="Title" class="form-label">Название роли</label>
                <span asp-validation-for="Name" class="text-danger"></span>
                <input type="text" asp-for="Name" class="form-control" id="Title">
            </div>
            <button type="submit" class="btn btn-success">Добавить</button>
        </form>
    </div>
</div>

BlogTask/Views/Role/Edit.cshtml
@model BlogTask.Models.Role.EditViewModel;

@{
    ViewData["Title"] = "Редактирование роли";
}

<partial name="_ValidationScriptsPartial" />

@if (Model is not null)
{
    <div class="container my-1">
        <div class="p-1">

            <h3>Изменить роль</h3>

            <form method="post" asp-controller="Role" asp-action="Edit">
                <div class="mb-3">
                    <label for="Name" class="form-label">Название</label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                    <input type="text" asp-for="Name" class="form-control" id="Name">
                </div>
                <div class="mb-3">
                    <label for="Description" class="form-label">Описание роли</label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                    <textarea type="text" asp-for="Description" class="form-control" id="Description"> </textarea>
                </div>
                <input type="text" asp-for="Id" hidden />
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
    </div>
}

BlogTask/Views/Role/Event.cshtml
@if (Model is not null)
{
    ViewData["Title"] = Model.Send;

    <div class="container my-1">
        <div class="p-1 text-center">
            <a asp-controller="Article" asp-action="Add">Добавить роль</a>
        </div>
    </div>
}
else
{
    ViewData["Title"] = "Предуприждение!";
}

BlogTask/Views/Role/List.cshtml
@model BlogTask.Models.Role.ListViewModel;

@{
    ViewData["Title"] = "Просмотр списка ролей";
}

@if (User.IsInRole("Администратор"))
{

    @if (Model.List.Count != 0)
    {
        <h3 class="text-center">Просмотр списка ролей</h3>
        @foreach (var role in @Model.List)
        {
            RouteValueDictionary get = new RouteValueDictionary();
            get["guid"] = role.Id.ToString();
            
            <div class="p-1">
                <div class="card">
                    <h5 class="card-header" cursor="pointer" role="button" onclick="location.href = '@Url.Action("View", get)'">@role.Name</h5>
                    <div class="card-body">
                        <p>@role.Description</p>
                    </div>
                </div>
            </div>
        }

    }
    @if (User.Identity.IsAuthenticated)
    {
        <div class="p-1">
            <button type="button" class="btn btn-success" onclick="window.location='@Url.Action("Add", "Role")'">Добавить</button>
        </div>
    }
}
else
{
    <p>Вы не являетесь администратором!</p>
}

BlogTask/Views/Role/ViewRole.cshtml
@{
    ViewData["Title"] = "Информация о роли";
}

@if (Model is not null)
{
    <div class="container my-1">
        <h3 class="text-center">Просмотр роли</h3>
        <div class="p-1">
            <div class="card rounded-3">
                <h5 class="card-header border-0">@Model.Name</h5>
                <div class="card-body">
                    @{
                        RouteValueDictionary get = new RouteValueDictionary();
                        get["guid"] = @Model.Id;
                    }
                    <h6>@Model.Description</h6>

                    @if (User.IsInRole("Администратор"))
                    {
                        <div class="p-1">
                            <button type="button" class="btn btn-outline-success btn-sm" onclick="window.location='@Url.Action("Edit", get)'">Редактировать</button>
                        
                            <button type="button" class="btn btn-outline-danger btn-sm" onclick="window.location='@Url.Action("Del", get)'">Удалить</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}